import pptxgen from "pptxgenjs";

// ---- Design tokens -------------------------------------------------------
const COLORS = {
  ink: "0F172A", // near-black navy for primary text
  accent: "6366F1", // indigo accent
  accentDark: "4338CA",
  accentSoft: "EEF2FF",
  bg: "0B1120", // dark cover background
  bgGradientEnd: "1E1B4B",
  muted: "64748B",
  line: "E2E8F0",
  white: "FFFFFF",
};

const FONT = "Poppins"; // falls back gracefully if unavailable on the rendering machine

// ---- Cover slide ----------------------------------------------------------
const addCover = (ppt, data) => {
  const slide = ppt.addSlide();
  slide.background = { color: COLORS.bg };

  // Diagonal accent band across the bottom for visual interest
  slide.addShape("rect", {
    x: -1,
    y: 4.3,
    w: 15.3,
    h: 3.5,
    fill: { color: COLORS.accentDark, transparency: 70 },
    rotate: -4,
    line: { type: "none" },
  });

  // Small eyebrow / kicker tag
  slide.addShape("roundRect", {
    x: 0.6,
    y: 0.6,
    w: 2.6,
    h: 0.4,
    rectRadius: 0.08,
    fill: { color: COLORS.accent },
    line: { type: "none" },
  });
  slide.addText("AI GENERATED OVERVIEW", {
    x: 0.6,
    y: 0.6,
    w: 2.6,
    h: 0.4,
    fontSize: 10,
    bold: true,
    color: COLORS.white,
    align: "center",
    valign: "middle",
    charSpacing: 1,
    fontFace: FONT,
  });

  // Accent rule above the title
  slide.addShape("line", {
    x: 0.65,
    y: 2.3,
    w: 1.1,
    h: 0,
    line: { color: COLORS.accent, width: 4 },
  });

  slide.addText(data.title || "Untitled", {
    x: 0.6,
    y: 2.5,
    w: "88%",
    h: 1.7,
    fontSize: 40,
    bold: true,
    color: COLORS.white,
    align: "left",
    fontFace: FONT,
    lineSpacing: 44,
  });

  if (data.subtitle) {
    slide.addText(data.subtitle, {
      x: 0.6,
      y: 4.05,
      w: "80%",
      h: 0.6,
      fontSize: 17,
      color: "C7D2FE",
      align: "left",
      fontFace: FONT,
    });
  }

  // Footer credit
  slide.addText("Generated by Multi AI Agent", {
    x: 0.6,
    y: "92%",
    w: 4,
    h: 0.4,
    fontSize: 10,
    color: "94A3B8",
    fontFace: FONT,
  });
};

// ---- Content slide ---------------------------------------------------------
const addContentSlides = (ppt, title, points = [], pageNum, totalPages) => {
  const slide = ppt.addSlide();
  slide.background = { color: COLORS.white };

  // Left accent rail
  slide.addShape("rect", {
    x: 0,
    y: 0,
    w: 0.18,
    h: "100%",
    fill: { color: COLORS.accent },
    line: { type: "none" },
  });

  // Numbered badge
  slide.addShape("ellipse", {
    x: 0.55,
    y: 0.5,
    w: 0.55,
    h: 0.55,
    fill: { color: COLORS.accentSoft },
    line: { color: COLORS.accent, width: 1 },
  });
  slide.addText(String(pageNum).padStart(2, "0"), {
    x: 0.55,
    y: 0.5,
    w: 0.55,
    h: 0.55,
    fontSize: 14,
    bold: true,
    color: COLORS.accentDark,
    align: "center",
    valign: "middle",
    fontFace: FONT,
  });

  // Heading
  slide.addText(title || "", {
    x: 1.3,
    y: 0.45,
    w: "80%",
    h: 0.7,
    fontSize: 26,
    bold: true,
    color: COLORS.ink,
    fontFace: FONT,
    valign: "middle",
  });

  // Divider under the header
  slide.addShape("line", {
    x: 0.55,
    y: 1.35,
    w: 12.2,
    h: 0,
    line: { color: COLORS.line, width: 1 },
  });

  // Bullet list with custom markers instead of default round bullets
  const startY = 1.75;
  const rowH = Math.min(0.85, 4.6 / Math.max(points.length, 1));

  points.forEach((text, idx) => {
    const y = startY + idx * rowH;

    slide.addShape("roundRect", {
      x: 0.6,
      y: y + rowH / 2 - 0.06,
      w: 0.12,
      h: 0.12,
      rectRadius: 0.03,
      fill: { color: COLORS.accent },
      line: { type: "none" },
    });

    slide.addText(text, {
      x: 0.95,
      y,
      w: "88%",
      h: rowH,
      fontSize: 17,
      color: COLORS.ink,
      fontFace: FONT,
      valign: "middle",
      breakLine: true,
    });
  });

  // Footer: page pill, bottom-right
  slide.addShape("roundRect", {
    x: 11.9,
    y: 6.95,
    w: 1.1,
    h: 0.35,
    rectRadius: 0.17,
    fill: { color: COLORS.accentSoft },
    line: { type: "none" },
  });
  slide.addText(`${pageNum} / ${totalPages}`, {
    x: 11.9,
    y: 6.95,
    w: 1.1,
    h: 0.35,
    fontSize: 10,
    bold: true,
    color: COLORS.accentDark,
    align: "center",
    valign: "middle",
    fontFace: FONT,
  });
};

// Returns the pptxgenjs instance itself (nothing written yet).
// Use this when you need a buffer (e.g. upload to S3) via ppt.write(...).
export const buildPpt = (data) => {
  if (!data || !Array.isArray(data.slides)) {
    throw new Error("buildPpt: `data.slides` must be an array");
  }

  const ppt = new pptxgen(); // <-- must use `new`

  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "Multi AI Agent";
  ppt.title = data.title;
  ppt.subject = data.title;
  ppt.company = "Multi AI Agent"; // was `comapny`
  ppt.theme = {
    // was `thema`
    headFontFace: FONT,
    bodyFontFace: FONT,
  };

  addCover(ppt, data);

  data.slides.forEach((s, i) => {
    // Support either { title, points } or { heading, point } slide shapes
    const heading = s.title ?? s.heading ?? "";
    const bullets = s.points ?? s.point ?? [];

    addContentSlides(ppt, heading, bullets, i + 1, data.slides.length);
  });

  return ppt;
};

// Convenience wrapper: builds the deck and writes it straight to disk.
export const generatePpt = async (data, fileName = "presentation.pptx") => {
  const ppt = buildPpt(data);
  return ppt.writeFile({ fileName });
};